name: clickhouse_dbt_project
version: "1.0.0"
profile: clickhouse_dbt_project  # must match the top key in profiles.yml
model-paths: ["models"]
macro-paths: ["macros", "dbt_packages/dbt_utils/macros"]
target-path: "target"
clean-targets: ["target"]

models:
  clickhouse_dbt_project:
    +materialized: table
