-- This macro returns full US state name based on the state code.

{% macro get_state_name(col) %}
CASE
    WHEN {{ col }} = 'AL' THEN 'Alabama'
    WHEN {{ col }} = 'AK' THEN 'Alaska'
    WHEN {{ col }} = 'AZ' THEN 'Arizona'
    WHEN {{ col }} = 'AR' THEN 'Arkansas'
    WHEN {{ col }} = 'CA' THEN 'California'
    WHEN {{ col }} = 'CO' THEN 'Colorado'
    WHEN {{ col }} = 'CT' THEN 'Connecticut'
    WHEN {{ col }} = 'DE' THEN 'Delaware'
    WHEN {{ col }} = 'FL' THEN 'Florida'
    WHEN {{ col }} = 'GA' THEN 'Georgia'
    WHEN {{ col }} = 'HI' THEN 'Hawaii'
    WHEN {{ col }} = 'ID' THEN 'Idaho'
    WHEN {{ col }} = 'IL' THEN 'Illinois'
    WHEN {{ col }} = 'IN' THEN 'Indiana'
    WHEN {{ col }} = 'IA' THEN 'Iowa'
    WHEN {{ col }} = 'KS' THEN 'Kansas'
    WHEN {{ col }} = 'KY' THEN 'Kentucky'
    WHEN {{ col }} = 'LA' THEN 'Louisiana'
    WHEN {{ col }} = 'ME' THEN 'Maine'
    WHEN {{ col }} = 'MD' THEN 'Maryland'
    WHEN {{ col }} = 'MA' THEN 'Massachusetts'
    WHEN {{ col }} = 'MI' THEN 'Michigan'
    WHEN {{ col }} = 'MN' THEN 'Minnesota'
    WHEN {{ col }} = 'MS' THEN 'Mississippi'
    WHEN {{ col }} = 'MO' THEN 'Missouri'
    WHEN {{ col }} = 'MT' THEN 'Montana'
    WHEN {{ col }} = 'NE' THEN 'Nebraska'
    WHEN {{ col }} = 'NV' THEN 'Nevada'
    WHEN {{ col }} = 'NH' THEN 'New Hampshire'
    WHEN {{ col }} = 'NJ' THEN 'New Jersey'
    WHEN {{ col }} = 'NM' THEN 'New Mexico'
    WHEN {{ col }} = 'NY' THEN 'New York'
    WHEN {{ col }} = 'NC' THEN 'North Carolina'
    WHEN {{ col }} = 'ND' THEN 'North Dakota'
    WHEN {{ col }} = 'OH' THEN 'Ohio'
    WHEN {{ col }} = 'OK' THEN 'Oklahoma'
    WHEN {{ col }} = 'OR' THEN 'Oregon'
    WHEN {{ col }} = 'PA' THEN 'Pennsylvania'
    WHEN {{ col }} = 'RI' THEN 'Rhode Island'
    WHEN {{ col }} = 'SC' THEN 'South Carolina'
    WHEN {{ col }} = 'SD' THEN 'South Dakota'
    WHEN {{ col }} = 'TN' THEN 'Tennessee'
    WHEN {{ col }} = 'TX' THEN 'Texas'
    WHEN {{ col }} = 'UT' THEN 'Utah'
    WHEN {{ col }} = 'VT' THEN 'Vermont'
    WHEN {{ col }} = 'VA' THEN 'Virginia'
    WHEN {{ col }} = 'WA' THEN 'Washington'
    WHEN {{ col }} = 'WV' THEN 'West Virginia'
    WHEN {{ col }} = 'WI' THEN 'Wisconsin'
    WHEN {{ col }} = 'WY' THEN 'Wyoming'
    ELSE 'Unknown'
END
{% endmacro %}
